version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: torrestrace_postgres
    restart: always
    environment:
      POSTGRES_DB: torrestrace
      POSTGRES_USER: torrestrace
      POSTGRES_PASSWORD: passwordzxc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
